VotingSystem/VotingSystem.Web/VotingSystem.Web.Admin/Models/Configuration/AdminUserConfiguration.cs
using System;

namespace VotingSystem.Web.Admin.Models.Configuration;

public class AdminUserConfiguration
{
    public Guid Id { get; set; }
    public string Name { get; set; }
    public string Email { get; set; }
    public string Password { get; set; }
}

VotingSystem/VotingSystem.Web/VotingSystem.Web.Admin/Models/ErrorViewModel.cs
namespace VotingSystem.Web.Admin.Models;

public class ErrorViewModel
{
    public string RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

VotingSystem/VotingSystem.Web/VotingSystem.Web.Admin/Controllers/HomeController.cs
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using VotingSystem.Domain.DTOs.Requests;
using VotingSystem.Web.Admin.Models;
using VotingSystem.Web.Admin.Services.Interfaces;

namespace VotingSystem.Web.Admin.Controllers;

public class HomeController : Controller
{
    private readonly IAuthService _authService;
    private readonly ILogger<HomeController> _logger;

    public HomeController(IAuthService authService, ILogger<HomeController> logger)
    {
        _authService = authService;
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> Index(LoginRequestDto loginRequestDto, string returnUrl = null)
    {
        if (!string.IsNullOrWhiteSpace(returnUrl))
            ViewBag.ReturnUrl = returnUrl;

        if (!ModelState.IsValid)
            return View(loginRequestDto);

        if (await _authService.LoginAsync(loginRequestDto.Email, loginRequestDto.Password))
            return RedirectToAction(nameof(Index), nameof(VotersController).Replace("Controller", ""));

        ViewBag.ErrorMessage = "Invalid email or password";
        return View(loginRequestDto);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> Logout()
    {
        await _authService.LogoutAsync();
        return RedirectToAction(nameof(Index));
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

VotingSystem/VotingSystem.Web/VotingSystem.Web.Admin/Controllers/PollsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using VotingSystem.Domain.DTOs.Requests;
using VotingSystem.Domain.DTOs.Responses;
using VotingSystem.Domain.Enums;
using VotingSystem.Infrastructure.Services.Interfaces;

namespace VotingSystem.Web.Admin.Controllers;

[Authorize]
public class PollsController : Controller
{
    private readonly IPollsService _pollsService;
    private readonly IVotersService _votersService;

    public PollsController(IPollsService pollsService, IVotersService votersService)
    {
        _pollsService = pollsService;
        _votersService = votersService;
    }

    public async Task<IActionResult> Index()
    {
        var polls = await _pollsService.GetAllAsync();

        return View(polls);
    }

    public async Task<IActionResult> Details(string id)
    {
        if (string.IsNullOrWhiteSpace(id))
            return RedirectToAction(nameof(Index));

        var poll = await _pollsService.GetByIdAsync(id);
        if (poll.ResponseCode != ResponseCode.Ok)
            return RedirectToAction(nameof(Index));

        if (DateTime.UtcNow >= poll.Data.StartDate) return View(poll.Data);
        
        var voters = await _votersService.GetAllAsync(false);
        voters.Data ??= new List<VoterResponseDto>();
        ViewData["Voters"] = voters.Data?.Where(v => v.IsActive).Select(v => new { v.Id, v.Email }).ToList();

        return View(poll.Data);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(
        [Bind("Title, Statement, StartDate, EndDate, Options")]
        PollRequestDto pollRequestDto)
    {
        var response = await _pollsService.CreateAsync(pollRequestDto);
        if (response.ResponseCode != ResponseCode.Ok)
            return View(pollRequestDto);
        return RedirectToAction(nameof(System.Index));
    }

    [HttpPost("{id}/give-right-to-vote")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> GiveRightToVote([FromRoute] string id,
        VoterGiveRightsToVoteDto voterGiveRightsToVoteDto)
    {
        var response = await _pollsService.AddRightsToVoteAsync(id, voterGiveRightsToVoteDto.VoterId);
        if (response.ResponseCode == ResponseCode.Ok)
        {
            TempData["Message"] = $"Se ha habilitado al usuario con correo {voterGiveRightsToVoteDto.Email} para participar en la votación.";
            TempData["MessageType"] = "success";
        }
        else
        {
            TempData["Message"] = $"Ha ocurrido un error al habilitar al usuario con correo {voterGiveRightsToVoteDto.Email}, por favor intente más tarde.";
            TempData["MessageType"] = "danger";
        }
        return RedirectToAction(nameof(Details), new { id });
    }
}

VotingSystem/VotingSystem.Web/VotingSystem.Web.Admin/Controllers/VotersController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using VotingSystem.Domain.DTOs.Requests;
using VotingSystem.Domain.Enums;
using VotingSystem.Infrastructure.Services.Interfaces;

namespace VotingSystem.Web.Admin.Controllers;

[Authorize]
public class VotersController : Controller
{
    private readonly IVotersService _votersService;

    /// <inheritdoc />
    public VotersController(IVotersService votersService)
    {
        _votersService = votersService;
    }

    public async Task<IActionResult> Index([FromQuery] string paginationToken)
    {
        var voters = await _votersService.GetAllAsync();

        return View(voters);
    }

    public async Task<IActionResult> Details(string id)
    {
        if (string.IsNullOrWhiteSpace(id))
            return RedirectToAction(nameof(Index));

        var voter = await _votersService.GetByIdAsync(id);
        if (voter.ResponseCode != ResponseCode.Ok)
            return RedirectToAction(nameof(Index));

        return View(voter.Data);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(
        [Bind("Name, Email, Department, City, Locality, Table")]
        VoterRequestDto voter)
    {
        try
        {
            var response = await _votersService.CreateAsync(voter);
            if (response.ResponseCode != ResponseCode.Created)
                return View(voter);

            return RedirectToAction(nameof(Index));
        }
        catch (Exception)
        {
            return BadRequest();
        }
    }
}

VotingSystem/VotingSystem.Web/VotingSystem.Web.Admin/Views/Home/Index.cshtml
@model LoginRequestDto

@{
    ViewData["Title"] = "Home Page";
    var returnUrl = string.Empty;
    if (!string.IsNullOrWhiteSpace(Context.Request.Query["ReturnUrl"]))
        returnUrl = Context.Request.Query["ReturnUrl"];
    if (!string.IsNullOrWhiteSpace(ViewBag.ReturnUrl))
        returnUrl = ViewBag.ReturnUrl;
}

<div class="row justify-content-center">
    <div class="col-md-6">
        <form asp-action="Index">
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control"/>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" type="password" class="form-control"/>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Iniciar Sesión" class="btn btn-primary btn-block"/>
            </div>
            <input type="hidden" name="ReturnUrl" value="@returnUrl"/>
        </form>
    </div>
</div>

VotingSystem/VotingSystem.Web/VotingSystem.Web.Admin/Views/Polls/Create.cshtml
@model PollRequestDto

<h1>Crear Consulta</h1>

<hr/>
<div class="row justify-content-center">
    <div class="col-md-6">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control"/>
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Statement" class="control-label"></label>
                <textarea asp-for="Statement" class="form-control"></textarea>
                <span asp-validation-for="Statement" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control"/>
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control"/>
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Options" class="control-label"></label>
                <button id="add-option" type="button" class="btn btn-info btn-sm">&#43;</button><br>
                <div id="options-container">
                    @if (Model is {Options: {Count: > 0}})
                    {
                        @foreach (var option in Model.Options)
                        {
                            <div class="input-group mb-3 option">
                                <input type="text" class="form-control" name="Options[]" value="@option">
                                <div class="input-group-append">
                                    <button class="btn btn-danger remove-option" type="button">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                        </svg>
                                    </button>
                                </div>
                            </div>
                        }
                    }
                    else
                    {
                        <div class="input-group mb-3 option">
                            <input type="text" class="form-control" name="Options[]">
                            <div class="input-group-append">
                                <button class="btn btn-danger" type="button">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                    </svg>
                                </button>
                            </div>
                        </div>
                    }
                </div>
                <span asp-validation-for="Options" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
        $("#add-option").click(function () {
            let html = '';
            html += '<div class="input-group mb-3 option">';
            html += '<input type="text" class="form-control" name="Options[]">';
            html += '<div class="input-group-append">';
            html += '<button class="btn btn-danger remove-option" type="button">';
            html += '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">';
            html += '<path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>';
            html += '<path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>';
            html += '</svg></button></div></div>';
    
            $('#options-container').append(html);
        });
    
        $(document).on('click', '.remove-option', function () {
            $(this).closest('.option').remove();
        });
    </script>
}

VotingSystem/VotingSystem.Web/VotingSystem.Web.Admin/Views/Polls/Details.cshtml
@model PollResponseDto

<div class="row justify-content-center">
    @if(!string.IsNullOrWhiteSpace(TempData["Message"] as string))
    {
        <div class="alert alert-@TempData["MessageType"] alert-dismissible fade show" role="alert">
            @TempData["Message"]
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
    <div class="col-md-6">
        <h2>@Model.Title</h2>
        <p>@Model.Statement</p>
        <p>
            <b>Fecha inicio:</b> @TimeZoneInfo.ConvertTime(Model.StartDate, TimeZoneInfo.FindSystemTimeZoneById("SA Pacific Standard Time")).ToString("MM/dd/yyyy hh:mm tt")
        </p>
        <p>
            <b>Fecha Fin:</b> @TimeZoneInfo.ConvertTime(Model.EndDate, TimeZoneInfo.FindSystemTimeZoneById("SA Pacific Standard Time")).ToString("MM/dd/yyyy hh:mm tt")
        </p>
        <p>
            <b>Opciones: </b>
        </p>
        <ul>
            @foreach (var option in Model.Options)
            {
                <li>@option.Value</li>
            }
        </ul>
        @if (DateTime.UtcNow < Model.StartDate)
        {
            <form asp-action="GiveRightToVote" asp-route-id="@Model.Address">
                <h3>Habilitar para votación</h3>
                <div class="form-group">
                    <input type="text" id="voter" placeholder="Email del votante" class="form-control"/>
                    <input id="voter-id" type="hidden" name="VoterGiveRightsToVoteDto.VoterId">
                    <input id="voter-email" type="hidden" name="VoterGiveRightsToVoteDto.Email">
                </div>
                <div class="form-group">
                    <input type="submit" value="Habilitar" class="btn btn-primary"/>
                </div>
            </form>
        }
    </div>
</div>

@if (DateTime.UtcNow < Model.StartDate)
{
    @section Scripts
    {
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap-4-autocomplete/dist/bootstrap-4-autocomplete.min.js" crossorigin="anonymous"></script>

        <script type="text/javascript">
            $("#voter").autocomplete({
                source: @Html.Raw(Json.Serialize(ViewData["Voters"])),
                highlightClass: 'text-danger',
                treshold: 2,
                label: 'email',
                value: 'id',
                onSelectItem: onSelectItem
            });
            
            function onSelectItem(item, element) {
                $('#voter-id').val(item.value);
                $('#voter-email').val(item.label);
            }
        </script>
    }
}

VotingSystem/VotingSystem.Web/VotingSystem.Web.Admin/Views/Polls/Index.cshtml
@model GenericResponseDto<IEnumerable<PollResponseDto>>

@{
    ViewData["Title"] = "Home Page";
}

<div class="row pt-3">
    <h3>Consultas</h3>
</div>

<div class="row">
    <p>
        <a class="btn btn-primary" asp-action="Create">Registrar Consulta</a>
    </p>
</div>

<div class="row justify-content-center">
    <div class="col-md-10">
        <table class="table table-striped table-bordered table-sm">
            <thead class="thead-dark">
            <tr>
                <th>
                    @Html.DisplayNameForInnerType((PollResponseDto p) => p.Title)
                </th>
                <th>
                    @Html.DisplayNameForInnerType((PollResponseDto p) => p.StartDate)
                </th>
                <th>
                    @Html.DisplayNameForInnerType((PollResponseDto p) => p.EndDate)
                </th>
                <th>Estado</th>
                <th>Acciones</th>
            </tr>
            </thead>
            <tbody>
            @if (Model.Data != null)
            {
                @foreach (var poll in Model.Data)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => poll.Title)
                        </td>
                        <td>
                            @TimeZoneInfo.ConvertTime(poll.StartDate, TimeZoneInfo.FindSystemTimeZoneById("SA Pacific Standard Time")).ToString("MM/dd/yyyy hh:mm tt")
                        </td>
                        <td>
                            @TimeZoneInfo.ConvertTime(poll.EndDate, TimeZoneInfo.FindSystemTimeZoneById("SA Pacific Standard Time")).ToString("MM/dd/yyyy hh:mm tt")
                        </td>
                        <td>
                            @if (poll.StartDate > DateTime.UtcNow)
                            {
                                <span class="badge badge-warning">Pendiente</span>
                            }
                            else if(poll.EndDate < DateTime.UtcNow)
                            {
                                <span class="badge badge-danger">Finalizada</span>
                            }
                            else
                            {
                                <span class="badge badge-success">En progreso</span>
                            }
                        </td>
                        <td>
                            <a asp-action="Details" asp-route-id="@poll.Address">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                                    <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"/>
                                    <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
                                </svg>
                            </a>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="5">No hay votaciones registradas</td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>

VotingSystem/VotingSystem.Web/VotingSystem.Web.Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - VotingSystem - Registraduría</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VotingSystem - Registraduría</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">

                    @{
                        System.Diagnostics.Debug.Assert(User.Identity != null, "User.Identity != null");
                    }
                    @if(User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Voters" asp-action="Index">Votantes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Polls" asp-action="Index">Votaciones</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        VotingSystem - Registraduría - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", false)
</body>
</html>

VotingSystem/VotingSystem.Web/VotingSystem.Web.Admin/Views/Voters/Create.cshtml
@model VoterRequestDto

<h1>Registrar votante</h1>

<hr/>
<div class="row justify-content-center">
    <div class="col-md-6">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control"/>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Department" class="control-label"></label>
                <input asp-for="Department" class="form-control"/>
                <span asp-validation-for="Department" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control"/>
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Locality" class="control-label"></label>
                <input asp-for="Locality" class="form-control"/>
                <span asp-validation-for="Locality" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Table" class="control-label"></label>
                <input asp-for="Table" class="form-control"/>
                <span asp-validation-for="Table" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

VotingSystem/VotingSystem.Web/VotingSystem.Web.Admin/Views/Voters/Details.cshtml
@model VoterResponseDto

<h1>Detalle del votante</h1>

<hr/>
<div class="row">
    <div class="col-6">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 text-primary">Información base</h6>
            </div>
            <div class="card-body">
                <dl class="row">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Name)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Name)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Email)
                    </dt>
                    <dd class="col-sm-12">
                        @Html.DisplayFor(model => model.Email)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.IsActive)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.IsActive)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Created)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Created)
                    </dd>
                </dl>
            </div>
        </div>
    </div>
    <div class="col-6">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 text-primary">Lugar de votación</h6>
            </div>
            <div class="card-body">
                <dl class="row">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Department)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Department)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.City)
                    </dt>
                    <dd class="col-sm-12">
                        @Html.DisplayFor(model => model.City)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Locality)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Locality)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Table)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Table)
                    </dd>
                </dl>
            </div>
        </div>
    </div>
</div>